### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by karlomikus**

### CODE REVIEW

**Comment by loffa** [comment]
Hey,

I see that you have added the translations I made. May I suggest waiting for a few days so that I will have time to look at all of them? Or do you prefer merging now and then again in a couple of days?

**Comment by karlomikus** [comment]
Hello,
PRs are created by crowdin. You can take your time, changes will be automatically added to this PR.

**Comment by loffa** [comment]
Oh great 👍

**Comment by loffa** [comment]
That should be 100% translated now :)

**Pull request merged**
